// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZEyDwXshiQj3CnI7fE4jJZ8ek8eYVPLU',
    appId: '1:439548906028:web:0be0c9365709dc314f1f89',
    messagingSenderId: '439548906028',
    projectId: 'cash-swift-10e31',
    authDomain: 'cash-swift-10e31.firebaseapp.com',
    storageBucket: 'cash-swift-10e31.appspot.com',
    measurementId: 'G-V1FYHQD52Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBW03S00Ypu9YDPh1KYwr54jDPywpcwJtc',
    appId: '1:439548906028:android:45e63dc0de664d584f1f89',
    messagingSenderId: '439548906028',
    projectId: 'cash-swift-10e31',
    storageBucket: 'cash-swift-10e31.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKgJ2tVY4oxKvMziW9PVCH2vLYyborvuc',
    appId: '1:439548906028:ios:de3dc4ea41a175fd4f1f89',
    messagingSenderId: '439548906028',
    projectId: 'cash-swift-10e31',
    storageBucket: 'cash-swift-10e31.appspot.com',
    iosBundleId: 'com.example.cashSwift',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKgJ2tVY4oxKvMziW9PVCH2vLYyborvuc',
    appId: '1:439548906028:ios:0edac97de025c5ec4f1f89',
    messagingSenderId: '439548906028',
    projectId: 'cash-swift-10e31',
    storageBucket: 'cash-swift-10e31.appspot.com',
    iosBundleId: 'com.example.cashSwift.RunnerTests',
  );
}
